# Generated by Django 5.2.1 on 2025-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_employee_branch_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
