# Generated by Django 5.2.1 on 2025-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
