# Generated by Django 5.2.1 on 2025-05-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_arrived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='loan',
            field=models.FloatField(default=0),
        ),
    ]
