# Generated by Django 5.2.1 on 2025-05-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_record_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='payed',
            field=models.FloatField(default=0),
        ),
    ]
