# Generated by Django 5.2.1 on 2025-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_record_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='price',
        ),
        migrations.AlterField(
            model_name='record',
            name='payed',
            field=models.FloatField(),
        ),
    ]
